In [2]:
import numpy as np
import pandas as pd

In [3]:
df = pd.read_excel("Central_Superstore.xlsx")  # لازم البيانات في نفس المكان

In [4]:
df

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,7981,CA-2011-103800,2013-01-03,2013-01-07,Standard Class,DP-13000,Darren Powers,Consumer,United States,Houston,...,77095,Central,OFF-PA-10000174,Office Supplies,Paper,"Message Book, Wirebound, Four 5 1/2"" X 4"" Form...",16.448,2,0.2,5.5512
1,740,CA-2011-112326,2013-01-04,2013-01-08,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,60540,Central,OFF-LA-10003223,Office Supplies,Labels,Avery 508,11.784,3,0.2,4.2717
2,741,CA-2011-112326,2013-01-04,2013-01-08,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,60540,Central,OFF-ST-10002743,Office Supplies,Storage,SAFCO Boltless Steel Shelving,272.736,3,0.2,-64.7748
3,742,CA-2011-112326,2013-01-04,2013-01-08,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,60540,Central,OFF-BI-10004094,Office Supplies,Binders,GBC Standard Plastic Binding Systems Combs,3.540,2,0.8,-5.4870
4,7661,CA-2011-105417,2013-01-07,2013-01-12,Standard Class,VS-21820,Vivek Sundaresam,Consumer,United States,Huntsville,...,77340,Central,FUR-FU-10004864,Furniture,Furnishings,"Howard Miller 14-1/2"" Diameter Chrome Round Wa...",76.728,3,0.6,-53.7096
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2318,6822,CA-2014-163860,2016-12-28,2017-01-01,Standard Class,LO-17170,Lori Olson,Corporate,United States,Peoria,...,61604,Central,FUR-FU-10001935,Furniture,Furnishings,3M Hangers With Command Adhesive,2.960,2,0.6,-1.4060
2319,7485,CA-2014-135111,2016-12-28,2017-01-02,Standard Class,CS-12400,Christopher Schild,Home Office,United States,Fargo,...,58103,Central,OFF-AR-10004707,Office Supplies,Art,Staples in misc. colors,2.480,1,0.0,0.8680
2320,7486,CA-2014-135111,2016-12-28,2017-01-02,Standard Class,CS-12400,Christopher Schild,Home Office,United States,Fargo,...,58103,Central,OFF-BI-10004040,Office Supplies,Binders,Wilson Jones Impact Binders,25.900,5,0.0,12.6910
2321,4240,CA-2014-158673,2016-12-29,2017-01-04,Standard Class,KB-16600,Ken Brennan,Corporate,United States,Grand Rapids,...,49505,Central,OFF-PA-10000994,Office Supplies,Paper,Xerox 1915,209.700,2,0.0,100.6560
2322,646,CA-2014-126221,2016-12-30,2017-01-05,Standard Class,CC-12430,Chuck Clark,Home Office,United States,Columbus,...,47201,Central,OFF-AP-10002457,Office Supplies,Appliances,Eureka The Boss Plus 12-Amp Hard Box Upright V...,209.300,2,0.0,56.5110

In [5]:
df.shape #  كام صف و عمود

(2323, 21)

In [6]:
df.head()  #  تظهر اول خمس صفوف الطبيعي الاى لو حددت

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,7981,CA-2011-103800,2013-01-03,2013-01-07,Standard Class,DP-13000,Darren Powers,Consumer,United States,Houston,...,77095,Central,OFF-PA-10000174,Office Supplies,Paper,"Message Book, Wirebound, Four 5 1/2"" X 4"" Form...",16.448,2,0.2,5.5512
1,740,CA-2011-112326,2013-01-04,2013-01-08,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,60540,Central,OFF-LA-10003223,Office Supplies,Labels,Avery 508,11.784,3,0.2,4.2717
2,741,CA-2011-112326,2013-01-04,2013-01-08,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,60540,Central,OFF-ST-10002743,Office Supplies,Storage,SAFCO Boltless Steel Shelving,272.736,3,0.2,-64.7748
3,742,CA-2011-112326,2013-01-04,2013-01-08,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,60540,Central,OFF-BI-10004094,Office Supplies,Binders,GBC Standard Plastic Binding Systems Combs,3.540,2,0.8,-5.4870
4,7661,CA-2011-105417,2013-01-07,2013-01-12,Standard Class,VS-21820,Vivek Sundaresam,Consumer,United States,Huntsville,...,77340,Central,FUR-FU-10004864,Furniture,Furnishings,"Howard Miller 14-1/2"" Diameter Chrome Round Wa...",76.728,3,0.6,-53.7096

In [7]:
df.head(10)  # هنا تظهر اول عشر صفوف

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,7981,CA-2011-103800,2013-01-03,2013-01-07,Standard Class,DP-13000,Darren Powers,Consumer,United States,Houston,...,77095,Central,OFF-PA-10000174,Office Supplies,Paper,"Message Book, Wirebound, Four 5 1/2"" X 4"" Form...",16.448,2,0.2,5.5512
1,740,CA-2011-112326,2013-01-04,2013-01-08,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,60540,Central,OFF-LA-10003223,Office Supplies,Labels,Avery 508,11.784,3,0.2,4.2717
2,741,CA-2011-112326,2013-01-04,2013-01-08,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,60540,Central,OFF-ST-10002743,Office Supplies,Storage,SAFCO Boltless Steel Shelving,272.736,3,0.2,-64.7748
3,742,CA-2011-112326,2013-01-04,2013-01-08,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,60540,Central,OFF-BI-10004094,Office Supplies,Binders,GBC Standard Plastic Binding Systems Combs,3.540,2,0.8,-5.4870
4,7661,CA-2011-105417,2013-01-07,2013-01-12,Standard Class,VS-21820,Vivek Sundaresam,Consumer,United States,Huntsville,...,77340,Central,FUR-FU-10004864,Furniture,Furnishings,"Howard Miller 14-1/2"" Diameter Chrome Round Wa...",76.728,3,0.6,-53.7096
5,7662,CA-2011-105417,2013-01-07,2013-01-12,Standard Class,VS-21820,Vivek Sundaresam,Consumer,United States,Huntsville,...,77340,Central,OFF-BI-10003708,Office Supplies,Binders,Acco Four Pocket Poly Ring Binder with Label H...,10.430,7,0.8,-18.2525
6,593,CA-2011-135405,2013-01-09,2013-01-13,Standard Class,MS-17830,Melanie Seite,Consumer,United States,Laredo,...,78041,Central,OFF-AR-10004078,Office Supplies,Art,Newell 312,9.344,2,0.2,1.1680
7,594,CA-2011-135405,2013-01-09,2013-01-13,Standard Class,MS-17830,Melanie Seite,Consumer,United States,Laredo,...,78041,Central,TEC-AC-10001266,Technology,Accessories,Memorex Micro Travel Drive 8 GB,31.200,3,0.2,9.7500
8,6327,CA-2011-167927,2013-01-20,2013-01-26,Standard Class,XP-21865,Xylona Preis,Consumer,United States,Westland,...,48185,Central,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,13.980,1,0.0,4.0542
9,6328,CA-2011-167927,2013-01-20,2013-01-26,Standard Class,XP-21865,Xylona Preis,Consumer,United States,Westland,...,48185,Central,FUR-FU-10002918,Furniture,Furnishings,Eldon ClusterMat Chair Mat with Cordless Antis...,272.940,3,0.0,30.0234

In [8]:
# head  بتجيب الصفوف من الاول من فوق طيب لو عايتشوف من تحت 
#يبقى استخدم tail

In [9]:
df.tail(10) #  اخر عشر صفوف من تحت

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
2313,954,CA-2014-136539,2016-12-28,2017-01-01,Standard Class,GH-14665,Greg Hansen,Consumer,United States,Round Rock,...,78664,Central,OFF-AR-10001958,Office Supplies,Art,Stanley Bostitch Contemporary Electric Pencil ...,27.1680,2,0.20,2.7168
2314,955,CA-2014-136539,2016-12-28,2017-01-01,Standard Class,GH-14665,Greg Hansen,Consumer,United States,Round Rock,...,78664,Central,FUR-BO-10004709,Furniture,Bookcases,"Bush Westfield Collection Bookcases, Medium Ch...",78.8528,2,0.32,-11.5960
2315,6819,CA-2014-163860,2016-12-28,2017-01-01,Standard Class,LO-17170,Lori Olson,Corporate,United States,Peoria,...,61604,Central,OFF-BI-10003784,Office Supplies,Binders,Computer Printout Index Tabs,1.6800,5,0.80,-2.6880
2316,6820,CA-2014-163860,2016-12-28,2017-01-01,Standard Class,LO-17170,Lori Olson,Corporate,United States,Peoria,...,61604,Central,FUR-FU-10004586,Furniture,Furnishings,G.E. Longer-Life Indoor Recessed Floodlight Bulbs,7.9680,3,0.60,-2.3904
2317,6821,CA-2014-163860,2016-12-28,2017-01-01,Standard Class,LO-17170,Lori Olson,Corporate,United States,Peoria,...,61604,Central,FUR-CH-10004698,Furniture,Chairs,"Padded Folding Chairs, Black, 4/Carton",113.3720,2,0.30,-3.2392
2318,6822,CA-2014-163860,2016-12-28,2017-01-01,Standard Class,LO-17170,Lori Olson,Corporate,United States,Peoria,...,61604,Central,FUR-FU-10001935,Furniture,Furnishings,3M Hangers With Command Adhesive,2.9600,2,0.60,-1.4060
2319,7485,CA-2014-135111,2016-12-28,2017-01-02,Standard Class,CS-12400,Christopher Schild,Home Office,United States,Fargo,...,58103,Central,OFF-AR-10004707,Office Supplies,Art,Staples in misc. colors,2.4800,1,0.00,0.8680
2320,7486,CA-2014-135111,2016-12-28,2017-01-02,Standard Class,CS-12400,Christopher Schild,Home Office,United States,Fargo,...,58103,Central,OFF-BI-10004040,Office Supplies,Binders,Wilson Jones Impact Binders,25.9000,5,0.00,12.6910
2321,4240,CA-2014-158673,2016-12-29,2017-01-04,Standard Class,KB-16600,Ken Brennan,Corporate,United States,Grand Rapids,...,49505,Central,OFF-PA-10000994,Office Supplies,Paper,Xerox 1915,209.7000,2,0.00,100.6560
2322,646,CA-2014-126221,2016-12-30,2017-01-05,Standard Class,CC-12430,Chuck Clark,Home Office,United States,Columbus,...,47201,Central,OFF-AP-10002457,Office Supplies,Appliances,Eureka The Boss Plus 12-Amp Hard Box Upright V...,209.3000,2,0.00,56.5110

In [10]:
df.info() # دي تجيب البيانات و ايه اللي فيها و تقولك معلومات علي اللبياناتا هامههههههههههه جدا

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2323 entries, 0 to 2322
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         2323 non-null   int64
 1   Order ID       2323 non-null   object
 2   Order Date     2323 non-null   datetime64[ns]
 3   Ship Date      2323 non-null   datetime64[ns]
 4   Ship Mode      2323 non-null   object
 5   Customer ID    2323 non-null   object
 6   Customer Name  2323 non-null   object
 7   Segment        2323 non-null   object
 8   Country        2323 non-null   object
 9   City           2323 non-null   object
 10  State          2323 non-null   object
 11  Postal Code    2323 non-null   int64
 12  Region         2323 non-null   object
 13  Product ID     2323 non-null   object
 14  Category       2323 non-null   object
 15  Sub-Category   2323 non-null   object
 16  Product Name   2323 non-null   object
 17  Sales          2323 non-null   float64
 18  Quantity       2323 non-null   int64
 19  Discount       2323 non-null   float64
 20  Profit         2323 non-null   float64
dtypes: datetime64[ns](2), float64(3), int64(3), object(13)
memory usage: 381.2+ KB

In [11]:
df.describe()

,Row ID,Order Date,Ship Date,Postal Code,Sales,Quantity,Discount,Profit
count,2323.000000,2323,2323,2323.000000,2323.000000,2323.000000,2323.000000,2323.000000
mean,5030.547998,2015-04-29 19:22:17.408523520,2015-05-03 20:45:58.501937152,65340.572536,215.772661,3.779595,0.240353,17.092709
min,15.000000,2013-01-03 00:00:00,2013-01-07 00:00:00,46060.000000,0.444000,1.000000,0.000000,-3701.892800
25%,2564.500000,2014-04-29 00:00:00,2014-05-05 00:00:00,55125.000000,14.620000,2.000000,0.000000,-5.664300
50%,5029.000000,2015-07-23 00:00:00,2015-07-27 00:00:00,65203.000000,45.980000,3.000000,0.200000,5.184000
75%,7612.500000,2016-05-09 12:00:00,2016-05-13 00:00:00,77041.000000,200.012000,5.000000,0.300000,22.456200
max,9984.000000,2016-12-30 00:00:00,2017-01-05 00:00:00,79907.000000,17499.950000,14.000000,0.800000,8399.976000
std,2923.638538,NaN,NaN,11427.949045,632.779010,2.160561,0.265433,291.487465

##### طب البيانات لو مش في مكان النوت بوك اعمل ايه 
df = pd.read_excel(" هنا حط ال path بتاع الداتاو متنساش اللسلاش  ")

 الللي جاي ده بقى كده بدانا analysis

MODULE 7: Pandas - Data Analysis Library

7.1 Introduction to Pandas

Pandas is the most important library for data analysis in Python. It provides:

* DataFrame: 2D labeled data structure (like Excel spreadsheet)
* Series: 1D labeled array
* Data cleaning and preprocessing tools
* Easy handling of missing data
* Reading/writing data from various formats (CSV, Excel, SQL, etc.)
* Powerful grouping and aggregation capabilities

In [12]:
# Import Pandas
import pandas as pd
import numpy as np

# Check version
print(f"Pandas version: {pd.__version__}")

Pandas version: 2.3.3

# 7.2 Series - 1D Labeled Array

In [13]:
# Creating Series from list
temperatures = pd.Series([23.5, 25.0, 22.8, 24.5, 26.2])
print("Temperature Series:")
print(temperatures)
print(f"\nData type: {temperatures.dtype}")

Temperature Series:
0    23.5
1    25.0
2    22.8
3    24.5
4    26.2
dtype: float64

Data type: float64

In [14]:
# Series with custom index
temps_labeled = pd.Series([23.5, 25.0, 22.8, 24.5, 26.2],
                          index=['Mon', 'Tue', 'Wed', 'Thu', 'Fri'])
print("\nLabeled Temperature Series:")
print(temps_labeled)

Labeled Temperature Series:
Mon    23.5
Tue    25.0
Wed    22.8
Thu    24.5
Fri    26.2
dtype: float64

In [15]:
# Accessing elements
print(f"\nMonday temperature: {temps_labeled['Mon']}")
print(f"First element (position): {temps_labeled.iloc[0]}")
print(f"\nWed-Fri temperatures:\n{temps_labeled['Wed':'Fri']}")

Monday temperature: 23.5
First element (position): 23.5

Wed-Fri temperatures:
Wed    22.8
Thu    24.5
Fri    26.2
dtype: float64

In [16]:
# Series from dictionary
population = pd.Series({
    'New York': 8336817,
    'Los Angeles': 3979576,
    'Chicago': 2693976,
    'Houston': 2320268
})
print("\nCity Population:")
print(population)
# Series operations
print(f"\nMean population: {population.mean():,.0f}")
print(f"Max population: {population.max():,}")
print(f"Total population: {population.sum():,}")

City Population:
New York       8336817
Los Angeles    3979576
Chicago        2693976
Houston        2320268
dtype: int64

Mean population: 4,332,659
Max population: 8,336,817
Total population: 17,330,637

# 7.3 DataFrame - 2D Labeled Data Structure

DataFrames are the heart of Pandas - think of them as Excel spreadsheets in Python!

In [45]:
# Creating DataFrame from dictionary
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve'],
    'Age': [25, 30, 35, 28, 32],
    'City': ['New York', 'Los Angeles', 'Chicago', 'Houston', 'Phoenix'],
    'Salary': [70000, 80000, 75000, 85000, 72000]
}
data

{'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve'],
 'Age': [25, 30, 35, 28, 32],
 'City': ['New York', 'Los Angeles', 'Chicago', 'Houston', 'Phoenix'],
 'Salary': [70000, 80000, 75000, 85000, 72000]}

In [46]:
df = pd.DataFrame(data)
print("Employee DataFrame:")
print(df)

Employee DataFrame:
      Name  Age         City  Salary
0    Alice   25     New York   70000
1      Bob   30  Los Angeles   80000
2  Charlie   35      Chicago   75000
3    David   28      Houston   85000
4      Eve   32      Phoenix   72000

In [47]:
df.columns

Index(['Name', 'Age', 'City', 'Salary'], dtype='object')

In [48]:
# الحصول على معلومات أساسية
print("\n=== DataFrame Information ===")
print(f"Shape: {df.shape}")           # يعرض عدد الصفوف وعدد الأعمدة
print(f"Columns: {df.columns.tolist()}") # يعرض أسماء الأعمدة الموجودة
print(f"Index: {df.index.tolist()}")   # يعرض الفهارس (عناوين الصفوف)
print(f"\nData types:\n{df.dtypes}")   # يعرض نوع البيانات في كل عمود

=== DataFrame Information ===
Shape: (5, 4)
Columns: ['Name', 'Age', 'City', 'Salary']
Index: [0, 1, 2, 3, 4]

Data types:
Name      object
Age        int64
City      object
Salary     int64
dtype: object

In [49]:
# First/Last rows
print("\nFirst 3 rows:")
print(df.head(3))

print("\nLast 2 rows:")
print(df.tail(2))

First 3 rows:
      Name  Age         City  Salary
0    Alice   25     New York   70000
1      Bob   30  Los Angeles   80000
2  Charlie   35      Chicago   75000

Last 2 rows:
    Name  Age     City  Salary
3  David   28  Houston   85000
4    Eve   32  Phoenix   72000

In [50]:
# Info and Description
print("\n=== DataFrame Info ===")
df.info()

print("\n=== Statistical Description ===")
print(df.describe())

=== DataFrame Info ===
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    5 non-null      object
 1   Age     5 non-null      int64
 2   City    5 non-null      object
 3   Salary  5 non-null      int64
dtypes: int64(2), object(2)
memory usage: 292.0+ bytes

=== Statistical Description ===
             Age        Salary
count   5.000000      5.000000
mean   30.000000  76400.000000
std     3.807887   6107.372594
min    25.000000  70000.000000
25%    28.000000  72000.000000
50%    30.000000  75000.000000
75%    32.000000  80000.000000
max    35.000000  85000.000000

### 7.4 Selecting and Filtering Data

In [51]:
# Continue with previous employee DataFrame

# Select single column (returns Series)
names = df['Name']
print("Names (Series):")
print(names)
print(f"Type: {type(names)}\n")

Names (Series):
0      Alice
1        Bob
2    Charlie
3      David
4        Eve
Name: Name, dtype: object
Type: <class 'pandas.core.series.Series'>

In [52]:
# Select multiple columns (returns DataFrame)
subset = df[['Name', 'Salary']]
print("Name and Salary:")
print(subset)
print(f"Type: {type(subset)}\n")

Name and Salary:
      Name  Salary
0    Alice   70000
1      Bob   80000
2  Charlie   75000
3    David   85000
4      Eve   72000
Type: <class 'pandas.core.frame.DataFrame'>

In [53]:
# Select rows by index position - iloc
print("First row (iloc[0]):")
print(df.iloc[0])
print("\nFirst 3 rows (iloc[0:3]):")
print(df.iloc[0:3])

First row (iloc[0]):
Name         Alice
Age             25
City      New York
Salary       70000
Name: 0, dtype: object

First 3 rows (iloc[0:3]):
      Name  Age         City  Salary
0    Alice   25     New York   70000
1      Bob   30  Los Angeles   80000
2  Charlie   35      Chicago   75000

In [54]:
# Select rows by label - loc هنا هتجيبي واحدو ثلاثه 
print("\nRows 1 and 3 (loc[[1, 3]]):")
print(df.loc[[1, 3]])

Rows 1 and 3 (loc[[1, 3]]):
    Name  Age         City  Salary
1    Bob   30  Los Angeles   80000
3  David   28      Houston   85000

In [55]:
# Boolean Filtering
print("\n=== Filtering Examples ===")
d=df['Age'] > 30
print(d)
# Employees older than 30
older_than_30 = df[df['Age'] > 30]
print("Employees older than 30:")
print(older_than_30)

=== Filtering Examples ===
0    False
1    False
2     True
3    False
4     True
Name: Age, dtype: bool
Employees older than 30:
      Name  Age     City  Salary
2  Charlie   35  Chicago   75000
4      Eve   32  Phoenix   72000

In [56]:
# Salary >= 75000
high_earners = df[df['Salary'] >= 75000]
print("\nHigh earners (>= $75,000):")
print(high_earners)

High earners (>= $75,000):
      Name  Age         City  Salary
1      Bob   30  Los Angeles   80000
2  Charlie   35      Chicago   75000
3    David   28      Houston   85000

In [57]:
 # Multiple conditions (AND - &)
filtered = df[(df['Age'] > 28) & (df['Salary'] > 75000)]
print("\nAge > 28 AND Salary > $75,000:")
print(filtered)

Age > 28 AND Salary > $75,000:
  Name  Age         City  Salary
1  Bob   30  Los Angeles   80000

In [58]:
# Multiple conditions (OR - |)
filtered_or = df[(df['City'] == 'New York') | (df['City'] == 'Chicago')]
print("\nEmployees in New York OR Chicago:")
print(filtered_or)

Employees in New York OR Chicago:
      Name  Age      City  Salary
0    Alice   25  New York   70000
2  Charlie   35   Chicago   75000

In [59]:
# Using isin()
cities_of_interest = ['New York', 'Chicago', 'Cairo']
filtered_isin = df[df['City'].isin(cities_of_interest)]
print("\nEmployees in specific cities:")
print(filtered_isin)

Employees in specific cities:
      Name  Age      City  Salary
0    Alice   25  New York   70000
2  Charlie   35   Chicago   75000

### 7.5 Adding, Modifying, and Deleting Columns

In [60]:
# Create a copy to work with
df_work = df.copy()

In [61]:
# Add new column
df_work['Bonus'] = df_work['Salary'] * 0.10
print("After adding Bonus column:")
print(df_work)

After adding Bonus column:
      Name  Age         City  Salary   Bonus
0    Alice   25     New York   70000  7000.0
1      Bob   30  Los Angeles   80000  8000.0
2  Charlie   35      Chicago   75000  7500.0
3    David   28      Houston   85000  8500.0
4      Eve   32      Phoenix   72000  7200.0

In [62]:
# Add column based on condition
df_work['Experience_Level'] = df_work['Age'].apply(lambda x: 'Senior' if x >= 30 else 'Junior')
print("\nAfter adding Experience_Level:")
print(df_work)

After adding Experience_Level:
      Name  Age         City  Salary   Bonus Experience_Level
0    Alice   25     New York   70000  7000.0           Junior
1      Bob   30  Los Angeles   80000  8000.0           Senior
2  Charlie   35      Chicago   75000  7500.0           Senior
3    David   28      Houston   85000  8500.0           Junior
4      Eve   32      Phoenix   72000  7200.0           Senior

In [63]:
# Modify existing column
df_work['Salary'] = df_work['Salary'] * 1.05  # 5% raise
print("\nAfter 5% salary increase:")
print(df_work[['Name', 'Salary']])

After 5% salary increase:
      Name   Salary
0    Alice  73500.0
1      Bob  84000.0
2  Charlie  78750.0
3    David  89250.0
4      Eve  75600.0

In [64]:
# Rename columns
df_work = df_work.rename(columns={'Salary': 'Annual_Salary', 'Age': 'Years_Old'})
print("\nAfter renaming columns:")
print(df_work.columns.tolist())
df_work

After renaming columns:
['Name', 'Years_Old', 'City', 'Annual_Salary', 'Bonus', 'Experience_Level']

      Name  Years_Old         City  Annual_Salary   Bonus Experience_Level
0    Alice         25     New York        73500.0  7000.0           Junior
1      Bob         30  Los Angeles        84000.0  8000.0           Senior
2  Charlie         35      Chicago        78750.0  7500.0           Senior
3    David         28      Houston        89250.0  8500.0           Junior
4      Eve         32      Phoenix        75600.0  7200.0           Senior

In [65]:
# Delete column
df_work = df_work.drop('Bonus', axis=1, inplace=True)
print("\nAfter dropping Bonus column:")
print(df_work.columns.tolist())

After dropping Bonus column:

AttributeError: 'NoneType' object has no attribute 'columns'

## 7.6 Handling Missing Data

In [66]:
# Create DataFrame with missing values
data_with_nulls = {
    'Product': ['A', 'B', 'C', 'D', 'E', 'F'],
    'Price': [10.5, np.nan, 15.0, 12.5, np.nan, 18.0],
    'Quantity': [100, 150, np.nan, 200, 175, 120],
    'Category': ['Electronics', 'Electronics', None, 'Clothing', 'Clothing', 'Electronics']
}

df_nulls = pd.DataFrame(data_with_nulls)
print("DataFrame with missing values:")
print(df_nulls)

DataFrame with missing values:
  Product  Price  Quantity     Category
0       A   10.5     100.0  Electronics
1       B    NaN     150.0  Electronics
2       C   15.0       NaN         None
3       D   12.5     200.0     Clothing
4       E    NaN     175.0     Clothing
5       F   18.0     120.0  Electronics

In [67]:
# Detect missing values
print("\nMissing values (True = missing):")
print(df_nulls.isnull())

Missing values (True = missing):
   Product  Price  Quantity  Category
0    False  False     False     False
1    False   True     False     False
2    False  False      True      True
3    False  False     False     False
4    False   True     False     False
5    False  False     False     False

In [68]:
# Detect missing values
print("\nMissing values (True = missing):")
print(df_nulls.isnull().sum())

Missing values (True = missing):
Product     0
Price       2
Quantity    1
Category    1
dtype: int64